Improve information in JobStatus error logging
in parsl 1.2.0:

Exception: 	STDOUT: /home/benc/parsl/src/parsl/runinfo/152/submit_scripts/parsl.localprovider.1666353855.5924258.sh: line 3: fjslfds: command not found


in parsl master before this PR:

2022-10-21 12:05:02 parsl.executors.status_handling:117 [ERROR]  Setting bad state due to exception
Exception: 	STDERR: /home/benc/parsl/src/parsl/runinfo/153/submit_scripts/parsl.localprovider.1666353901.5586867.sh: line 3: fjslfds: command not found