https://github.com/Parsl/parsl/issues/2232 reports what looks like race conditions in access to the ready_managers structure
investigate that...

RuntimeError: dictionary changed size during iteration

so the error here is about managers registering and unregistering

this is going to happen with lots of managers registering and unregistering, in a HTC-style workflow with lots of small blocks

but I wonder how hard it is to reproduce in my dev environment?